[IMP]  sale_order_import_edifact: EDIFACT formats support
thienvh332/edi pull request #2
Opened 2023-10-23 11:34 UTC by thienvh332

2023-10-24 02:54 UTC, nilshamerlinck requested changes

2023-10-24 02:54 UTC, nilshamerlinck commented on sale_order_import_edifact/wizard/sale_order_import.py
> +                }
```suggestion
            partner_dict["edi_ctx"] = {
                "order_filename": self.order_filename,
            }
            if references.get("vat"):
                partner_dict["edi_ctx"]["rff_va"] = references["vat"]
```

2023-10-24 11:47 UTC, thienvh332 commented on sale_order_import_edifact/wizard/sale_order_import.py
> +                }
Thanks @nilshamerlinck , updated.

2023-10-25 03:03 UTC, nilshamerlinck approved these changes

2024-03-06 07:08 UTC, closed without merging